// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/aa50ecddf9d9c8d2a4ce584f50482f32f6eb848f/body-parser/index.d.ts
declare module 'body-parser' {
// Type definitions for body-parser 1.16
// Project: https://github.com/expressjs/body-parser
// Definitions by: Santi Albo <https://github.com/santialbo>, Vilic Vane <https://github.com/vilic>, Jonathan Häberle <https://github.com/dreampulse>, Gevik Babakhani <https://github.com/blendsdk/>, Tomasz Łaziuk <https://github.com/tlaziuk>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped

/// <reference types="node" />

import { Request, RequestHandler, Response } from 'express';

// for docs go to https://github.com/expressjs/body-parser/tree/1.16.0#body-parser

// @deprecated
function bodyParser(options?: bodyParser.OptionsJson & bodyParser.OptionsText & bodyParser.OptionsUrlencoded): RequestHandler;

namespace bodyParser {
    interface Options {
        inflate?: boolean;
        limit?: number | string;
        type?: string | ((req: Request) => any);
        verify?: (req: Request, res: Response, buf: Buffer, encoding: string) => void;
    }

    interface OptionsJson extends Options {
        reviever?: (key: string, value: any) => any;
        strict?: boolean;
    }

    interface OptionsText extends Options {
        defaultCharset?: string;
    }

    interface OptionsUrlencoded extends Options {
        extended?: boolean;
        parameterLimit?: number;
    }

    function json(options?: OptionsJson): RequestHandler;

    function raw(options?: Options): RequestHandler;

    function text(options?: OptionsText): RequestHandler;

    function urlencoded(options?: OptionsUrlencoded): RequestHandler;
}

export = bodyParser;
}
